name: Trydent CI/CD

on:
  pull_request:
    branches:
      - dev
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Testing Code
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm run test
        continue-on-error: true
